version: "3"
services:
    db:
        image: mongo
        ports:
            - "27017:27017"
    web:
        container_name: "node-mongo"
        build: .
        ports:
            - "8081:8085"
        env_file: .env
        links:
            - db
